---
  - name: "Upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "Remove unneeded deps"
    become: yes
    apt:
      autoremove: yes

  - name: "Install nodejs and npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "Install nvm"
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: "Install node v13.8.0"
    become: yes
    shell: n 13.8.0

  - name: "Install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present