- name: extract backend artifacts
  unarchive:
    src: artifact-backend.tar.gz
    dest: ~/

- name: Start backend
  shell: |
    cd ~/artifact-backend
    npm install
    pm2 stop default
    pm2 start npm -- start
