- name: "install Prometheus"
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: '0777'
    
- name: Creates directory
  file:
    path: /etc/prometheus
    state: directory
    
- name: "add prometheus.yml"
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    
- name: "add rule configuration."
  become: true
  copy:
    src: rule.yml
    dest:  /etc/prometheus/rule.yml
    
- name: "add prometheus configuration."
  become: true
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
   
- name: "enable prometheus service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: prometheus
    enabled: yes
